### ISSUE TITLE
`printRuntimeInterfaceCombinator` doesn't propagate `name` to `intersectionCombinator`

### ISSUE THREAD

**Issue by gabejohnson** [gcanti/io-ts-codegen#31]
While attempting to give custom names to my types, I noticed that some of my codices receive the name, while others do not. It turns out that those with optional properties are the ones that don't.

I believe I've tracked this down to https://github.com/gcanti/io-ts-codegen/blob/30f6374b08ab0fc2928f6b66185f266d84132258/src/index.ts#L600-L610

Notice that `ic.name` is not being passed down `intersectionCombinator`.

I can submit a PR if you'd like.

**Comment by gabejohnson** [comment]
https://github.com/gcanti/io-ts-codegen/blob/30f6374b08ab0fc2928f6b66185f266d84132258/src/index.ts#L703-L707

It may be worth passing `name` to `t.readonly` as well.

**Comment by gcanti** [comment]
@gabejohnson good catch, thanks for the bug report!

> It may be worth passing `name` to `t.readonly` as well

Maybe, I'm not sure about that. IMO I should drop the `isReadonly` boolean and add an explicit `ReadonlyCombinator`

**Comment by gcanti** [comment]
> I should drop the `isReadonly` boolean and add an explicit `ReadonlyCombinator`

@gabejohnson in the meanwhile which name should I use for `t.readonly` in your opinion? `declaration.name`?

**Comment by gabejohnson** [comment]
> which name should I use for `t.readonly` in your opinion? `declaration.name`?

That was my thinking

**Comment by gcanti** [comment]
@gabejohnson released a patch, let me know if it works for you

**Comment by gabejohnson** [comment]
Thanks for addressing this so quickly!

**Comment by gabejohnson** [comment]
> Maybe, I'm not sure about that. IMO I should drop the `isReadonly` boolean and add an explicit `ReadonlyCombinator`

I agree

**Comment by gcanti** [comment]
@gabejohnson https://github.com/gcanti/io-ts-codegen/releases/tag/0.3.2
