### ISSUE TITLE
Cannot reference a CustomTypeDeclaration

### ISSUE THREAD

**Issue by sledorze** [gcanti/io-ts-codegen#34]
`TypeReference` is defined as `BasicType | Combinator | Identifier`

This does not includes `CustomTypeDeclaration` which prevents the usage of the latter as a parameter of `typeDeclaration` to build a Type Declaration (and export it).

@gcanti I can make a PR if this looks acceptable to you.

**Comment by gcanti** [comment]
@sledorze that's correct, you must refer to a custom type declaration by using an `identifier`, see this test for an example https://github.com/gcanti/io-ts-codegen/blob/aed194c18bfc15299d6fd7778bd9fb552b1d4215/test/sort.ts#L7

**Comment by sledorze** [comment]
Thanks @gcanti
