### ISSUE TITLE
Dependency update to io-ts@2.0.0

### ISSUE THREAD

**Issue by SAnDAnGE** [gcanti/io-ts-codegen#44]
npm WARN io-ts-codegen@0.4.0 requires a peer of io-ts@^1.8.1 but none is installed. You must install peer dependencies yourself.

**Comment by gcanti** [comment]
Actually I'm not sure why there is such a dependency in the first place

**Comment by SAnDAnGE** [comment]
Probably to make sure the generated code is compatible with that specific version and doesn't break the compatibility ? :)
