### ISSUE TITLE
Duplicate declarations are silently deleted by gen.sort

### ISSUE THREAD

**Issue by cyberixae** [gcanti/io-ts-codegen#59]
I encountered a problem where two declarations had the same name and one of them silently disappeared during sort.

```typescript
it('should not discard duplicate declarations', () => {
  const declarations: Array<t.TypeDeclaration> = [
    t.typeDeclaration('A', t.stringType),
    t.typeDeclaration('A', t.numberType)
  ]
  const tds = t.sort(declarations)
  assert.strictEqual(tds.length, 2)
})
```

**Comment by gcanti** [comment]
@cyberixae thanks for reporting. Names can't be duplicated, so I'm not sure what `sort` should do other than throwing a `new Error('duplicated name: A')`

**Comment by cyberixae** [comment]
An explicit error would be better than silent failure. The other option would be to preserve the order of the duplicate inputs. That way the sort function would be well defined for all inputs.
